name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.w1RUOZXyexjXem_CIdAG52xs9WZQSgSGHGvuFpOo }}
          accountId: ${{ secrets.232d9ee5139c436b2f2fe9cf87b8a3c8 }}
